---
name: Reusable workflow get artifact

on:
  workflow_call: 

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v5
      with:
        name: my-artifact-c1    
    - run: |
          pwd 
          ls -lart 
