---
name: Reusable workflow c

on:
  workflow_call: 

jobs:
  build-c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        pwd
        ls -lart 
        gcc --version
        gcc -o testc testc.c 
        ./testc 
    - name: check_lint_c
      run: |
        sudo pipx install cpplint
        pipx ensurepath --force
        which cpplint
        cpplint testc.c
      continue-on-error: true
