---
name: Reusable workflow c

on:
  workflow_call: 

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        pwd
        ls -lart 
        #gcc --version
        #gcc -o testc test.c 
            
  
        
