---
name: Reusable workflow c

on:
  workflow_call: 

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
    - run: ¦ 
        gcc --version
        gcc -o testc test.c 
            
  
        
