---
name: Reusable workflow api

on:
  workflow_call: 

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
    - name: "get_myip" 
      id : get_myip
      run: |
            IP=$(curl --version | grep libcurl  2>&1 1>/dev/null &&   curl -s https://api.ipify.org?format=json | jq .ip  | sed -e 's/"//g')
            echo $IP
            echo "IP=$IP" >> $GITHUB_OUTPUT
            echo "IP inside step: $IP"
      env:
        MYIP: ${{ steps.get_myip.outputs.IP }}
    - run: echo ${{ steps.get_myip.outputs.IP }} 
            
  
        
