---
name: Reusable workflow c

on:
  workflow_call: 

jobs:
  build-c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        pwd
        ls -lart 
        gcc --version
        gcc -o testc testc.c 
        ./testc 
    - uses: actions/upload-artifact@v7
      with:
        name: my-artifact-c1
        path: testc
  
        
